Docs: Add a PuppyGraph Integration Guide
unitycatalog/unitycatalog pull request #360
Opened 2024-08-19 08:39 UTC by FreeMem17

**PR Checklist**

- [x] A description of the changes is added to the description of this PR.
- [x] If there is a related issue, make sure it is linked to this PR.
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added or modified a feature, documentation in `docs` is updated

**Description of changes**

- Documentation change only
- Add a page for integration of  Unity Catalog and PuppyGraph

2024-08-19 11:41 UTC, michelleon requested changes
@dennyglee to take a look

other than the one change in the header it looks good to me

2024-08-19 11:41 UTC, michelleon commented on docs/integrations/unity-catalog-puppygraph.md
> +# Unity Catalog XTable Integration
should be PuppyGraph integration

2024-08-19 18:17 UTC, FreeMem17 commented on docs/integrations/unity-catalog-puppygraph.md
> +# Unity Catalog XTable Integration
Ah! Good catch.

2024-08-20 13:11 UTC, dennyglee approved these changes
This looks great!  A non-blocking suggestion would be to add some screenshots to PuppyGraph UI to the docs as well.  But this should be done in a different PR.

2024-08-20 18:23 UTC, FreeMem17 commented
> This looks great! A non-blocking suggestion would be to add some screenshots to PuppyGraph UI to the docs as well. But this should be done in a different PR.

Thank you Denny. I will add them in a separate PR. Is there a general recommendation on image dimension / file size?

2024-08-20 22:51 UTC, dennyglee approved these changes

2024-08-20 22:53 UTC, merged

2024-08-22 13:39 UTC, dennyglee commented
> > This looks great! A non-blocking suggestion would be to add some screenshots to PuppyGraph UI to the docs as well. But this should be done in a different PR.
> 
> Thank you @dennyglee. I will add them in a separate PR. Is there a general recommendation on image dimension / file size?

Oh sorry for missing this, GitHub has a max size of 10MB but I would recommend it to be smaller closer to GitHub's [Social Media Preview](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/customizing-your-repositorys-social-media-preview#).  HTH!