[DOCKER] Use assembly jars for UC images
unitycatalog/unitycatalog pull request #367
Opened 2024-08-20 21:17 UTC by jaceklaskowski

As reported in https://github.com/unitycatalog/unitycatalog/issues/339, Docker containers fail to start after a successful docker image build.

This is due to [this](https://github.com/unitycatalog/unitycatalog/commit/119f4707d033add34c0894916f544785e110fe94) and [this](https://github.com/unitycatalog/unitycatalog/commit/009ac77e7cd7926acb061ed1b8b5c3e5177c1bf7) commits that introduced assembly jars with incomplete metadata (`mainClass`).

This PR is supposed to fix https://github.com/unitycatalog/unitycatalog/issues/339 with some extra (opinionated) changes like:

1. UC CLI container accepts regular CLI options
2. No more `network` and `volume` (which may or may not be useful but turned out a nightmare to make right to achieve the above)

There are some FIXMEs left to work on in followup PRs 😉

2024-08-22 13:27 UTC, dennyglee commented
Thanks @jaceklaskowski  - reviewing this now :)

2024-08-22 16:42 UTC, dennyglee requested changes
Thanks @jaceklaskowski  - I really like the smoother flow of this docker readme.  Some clarifications in the `readme.md`.  Thanks!

2024-08-22 16:42 UTC, dennyglee commented on docker/README.md
> +Execute `start-uc-cli-in-docker` to connect to the Unity Catalog server on your local machine (`localhost`).
This was already done in L35

2024-08-26 15:41 UTC, jaceklaskowski commented
Back to the game after a short holiday...

2024-08-26 16:42 UTC, jaceklaskowski commented
Think all the nits were addressed and the PR is ready for another review @dennyglee 🙏

2024-08-28 03:58 UTC, dennyglee commented on docker/README.md
> +```console
Thanks a bunch!

2024-08-28 04:03 UTC, dennyglee approved these changes
This looks great, thanks a bunch for tackling this @jaceklaskowski

2024-08-28 04:03 UTC, merged