docs: add docs for ORC tables
unitycatalog/unitycatalog pull request #388
Opened 2024-08-28 20:13 UTC by avriiil

This PR adds a documentation page that shows users how to work with ORC tables. Will close #206

2024-09-02 09:56 UTC, avriiil commented on docs/usage/tables/orc.md
> +After you run the `table create` command, your output should look something like this:
Yes, done!

2024-09-02 09:57 UTC, avriiil commented
Thanks for the review @jaceklaskowski ! I've incorporated your suggestions.

2024-09-05 20:55 UTC, jaceklaskowski requested changes

2024-09-05 20:55 UTC, jaceklaskowski commented on docs/usage/tables/orc.md
> +Let's take a look at how we can create ORC tables in Unity Catalog.
Remove it = redundant

2024-09-05 20:55 UTC, jaceklaskowski commented on docs/usage/tables/orc.md
> +This page explains how you can work with ORC tables in your Unity Catalog.
Remove `your`

2024-09-05 20:55 UTC, jaceklaskowski commented on docs/usage/tables/orc.md
> +Use the following command to create an external ORC tables (at `path/to/storage` location) with 2 colummns: `some_numbers` and `some_letters`.
Can you match this PR to the AVRO's, please? 🙏  The pages should really be identical, shouldn't they?

2024-09-12 10:20 UTC, avriiil commented
@jaceklaskowski @MrPowers - this is ready for another pass. Layout now matches with Avro page.

2024-09-20 16:55 UTC, MrPowers approved these changes
LGTM

2024-09-20 16:55 UTC, merged