Supported compute engines section updated: Issue#1
unitycatalog/unitycatalog pull request #40
Opened 2024-06-15 02:40 UTC by vinijaiswal

2024-06-15 14:28 UTC, ramesh-db approved these changes

2024-06-15 15:22 UTC, dennyglee requested changes
Thanks @vinijaiswal - could you update it to remove Presto and include Starburst?  The missing Spark and Starburst logos were an oversight on our part.  We haven't had a chance to chat with the Presto community yet.

2024-06-16 21:12 UTC, vinijaiswal commented
Thanks for reviewing and providing the background, @dennyglee. I updated the requested changes.

2024-06-17 15:21 UTC, dennyglee approved these changes
Thanks @vinijaiswal - LGTM!

2024-06-17 15:35 UTC, merged