Merge unitycatalog-ui to this repo under the ui directory
unitycatalog/unitycatalog pull request #412
Opened 2024-09-05 06:41 UTC by tdas

**PR Checklist**

- [x] A description of the changes is added to the description of this PR.
- [ ] If there is a related issue, make sure it is linked to this PR.
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added or modified a feature, documentation in `docs` is updated

**Description of changes**

This PR moves all the code and commit history in the current github.com/unitycatalog/unitycatalog-ui repo to this repo, under the UI directory. This has a bunch of redundant files like .gitignore, CONTRIBUTING, etc. which can be removed later once these commits have been non-squash merged while preserving history.

2024-09-05 13:56 UTC, dennyglee approved these changes

2024-09-05 14:00 UTC, dennyglee requested changes
Checking...

2024-09-05 16:05 UTC, robertgv commented
@tdas @dennyglee The LICENSE, CONTRIBUTIG and CODE_OF_CONDUCT documents are already on the base of this repo. I think they can be excluded on this PR.

2024-09-06 13:53 UTC, dennyglee commented
Closing as this was resolved with #421

2024-09-06 13:53 UTC, closed without merging