ucai-core lib with base UC function client
unitycatalog/unitycatalog pull request #536
Opened 2024-10-01 09:32 UTC by serena-ruan

**PR Checklist**

- [ ] A description of the changes is added to the description of this PR.
- [ ] If there is a related issue, make sure it is linked to this PR.
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added or modified a feature, documentation in `docs` is updated

**Description of changes**
Based on https://github.com/unitycatalog/unitycatalog/issues/525:
- Implement base UC function client

2024-10-01 09:47 UTC, serena-ruan commented
@BenWilson2 Could you take a look at this PR?

2024-10-08 00:31 UTC, serena-ruan commented
@dennyglee Hey Denny, could you take a look at this and see this folder make sense?

2024-10-08 01:52 UTC, BenWilson2 commented on unitycatalog-ai/README.md
> +The Unity Catalog AI Core library provides convenient APIs to interact with Unity Catalog functions, including functions creation, retrieval and execution.
```suggestion
The Unity Catalog AI Core library provides convenient APIs to interact with Unity Catalog functions, including the creation, retrieval and execution of functions.
```

2024-10-08 01:55 UTC, BenWilson2 commented on unitycatalog-ai/src/ucai/core/client.py
> +    Value is always string, even if the function returns a scalar.
```suggestion
    Value is always string, even if the function returns a scalar or a collection.
```

2024-10-08 01:58 UTC, dennyglee requested changes
Minor clarifications requested; the structure looks great!  Thanks @serena-ruan !

2024-10-08 01:58 UTC, dennyglee commented on unitycatalog-ai/LICENSE.txt
The root will have a `LICENSE.txt` so we should not include this license as well.

2024-10-08 01:58 UTC, dennyglee commented on unitycatalog-ai/README.md
Minor nit, could you clarify that ucai is part of the client interface for executing functions to support agents?

2024-10-08 02:02 UTC, BenWilson2 approved these changes
LGTM! Solid scaffolding :)

2024-10-08 03:06 UTC, dennyglee approved these changes

2024-10-08 03:06 UTC, merged