[DOCS] update homepage for v0.2
unitycatalog/unitycatalog pull request #579
Opened 2024-10-09 05:22 UTC by avriiil

This PR updates the home page in the docs to reflect changes in v0.2

2024-10-10 06:07 UTC, vikrantpuppala approved these changes
Thanks! Can you please signoff on the commits to pass the DCO check

2024-10-10 12:51 UTC, ebyhr commented on docs/index.md
> +- Authentication/Authorization capabilitities,
```suggestion
- Authentication/Authorization capabilitities
```

2024-10-11 01:12 UTC, dennyglee requested changes

2024-10-11 01:12 UTC, dennyglee commented on docs/index.md
> +The first release of Unity Catalog focused on a core set of APIs for tables, unstructured data, and AI assets. The [second release (v0.2)](https://github.com/unitycatalog/unitycatalog/releases/tag/v0
Could you reword this so we no longer refer to UC releases since it's the docs?  Just call out the overall main components as of the latest release?

2024-10-15 18:49 UTC, avriiil commented
closing this in favor of [#613](https://github.com/unitycatalog/unitycatalog/pull/613) with signed-off commits

2024-10-15 18:49 UTC, closed without merging