Remove unused method
unitycatalog/unitycatalog pull request #636
Opened 2024-10-19 12:04 UTC by ebyhr

**PR Checklist**

- [x] A description of the changes is added to the description of this PR.
- [ ] If there is a related issue, make sure it is linked to this PR.
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added or modified a feature, documentation in `docs` is updated

**Description of changes**

Remove unused method

2024-10-20 13:57 UTC, jaceklaskowski requested changes
Please merge it with https://github.com/unitycatalog/unitycatalog/pull/637 🙏

2024-10-21 12:02 UTC, kriscon-db approved these changes
Removed model and URI methods are safe to remove.  They were initially added by with the idea that they would be needed in the initial model support PRs but it turns out we didn't need them/won't need them and I just forgot to remove.  Thanks for doing this!

cc @creechy on the User method though.

2024-10-22 15:57 UTC, creechy approved these changes

2024-10-22 19:50 UTC, tdas approved these changes

2024-10-22 19:50 UTC, merged

2024-10-22 19:51 UTC, tdas commented
thank you @ebyhr