[DOCS] Added mkdocs explanation to docs README.md
unitycatalog/unitycatalog pull request #645
Opened 2024-10-22 16:53 UTC by Brijeshthummar02

**PR Checklist**

- [ ] A description of the changes is added to the description of this PR.
- [ ] If there is a related issue, make sure it is linked to this PR.
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added or modified a feature, documentation in `docs` is updated

**Description of changes**

Added file to docs/README.md
issue #550

2024-10-22 16:54 UTC, Brijeshthummar02 commented
@dennyglee have a look.

2024-10-22 19:49 UTC, HorizonNet commented
Failing `Docs Generation Tests` will be resolved with the changes proposed in #646.

2024-10-23 05:03 UTC, dennyglee approved these changes
LGTM overall but just noticed the conflicts @Brijeshthummar02 - could you take a quick Look at this as well as address the DCO issue?  Thanks!

2024-10-23 05:05 UTC, dennyglee requested changes
Per readme conflict

2024-10-23 14:56 UTC, closed without merging

2024-10-23 14:56 UTC, HorizonNet commented on mkdocs.yml
> -exclude_docs: |
@Brijeshthummar02 Please leave as is. This definitely works and with the update the doc test is failing again.