[Docs] Update CLI page formatting
unitycatalog/unitycatalog pull request #770
Opened 2024-11-29 12:51 UTC by avriiil

This PR updates the formatting of the CLI docs page to be more like the Models page. Will close #515.

Signed-off-by: Avril Aysha <68642378+avriiil@users.noreply.github.com>

2024-11-29 14:17 UTC, HorizonNet commented
@avriiil Before going into detail, are you sure that this should link to #515?

2024-11-30 12:49 UTC, avriiil commented
@HorizonNet - good catch, should be #545, I've corrected it.

2024-12-01 14:31 UTC, HorizonNet requested changes
Left a few comments regarding code snippet formatting. Rest LGTM.

2024-12-01 14:31 UTC, HorizonNet commented on docs/usage/cli.md
> +```sh
Use `console` instead for console outputs.

2024-12-01 14:31 UTC, HorizonNet commented on docs/usage/cli.md
>  ```sh
Use `console` instead for console outputs.

2024-12-01 14:31 UTC, HorizonNet commented on docs/usage/cli.md
> +```bash title="List registered models"
Use `sh` instead to stay consistent. Also applies to the other code snippets below.

2024-12-15 16:48 UTC, HorizonNet approved these changes
LGTM

2024-12-17 01:46 UTC, dennyglee approved these changes
Oh, this looks great - thanks!

2024-12-17 01:53 UTC, merged